name: iiq3782
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - notebook
  - numpy
  - pandas
  - matplotlib
  - phasepy
  - numpy
  - scipy=1.11.4
  - cython
  - setuptools
  - python-ternary
  - openpyxl
  - xlsxwriter
  - numba
